server:
  port: 8769
#本地
#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#    active: native

#git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiushigao/springcloud-config
          username: 2836428900@qq.com
          password: wangjie037413
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
